export const PERMISSIONS = {
  POST: {
    ADD_POST: "add_post",
    VIEW_ALL_POSTS: "view_all_posts",
    EDIT_POST: "edit_post",
    DELETE_POST: "delete_post",
    TOGGLE_ACTIVE_POST: "toggle_active_post",
    TOGGLE_FEATURED_POST: "toggle_featured_post",
  },
  CATEGORY: {
    ADD_CATEGORY: "add_category",
    VIEW_ALL_CATEGORIES: "view_all_categories",
    EDIT_CATEGORY: "edit_category",
    DELETE_CATEGORY: "delete_category",
    TOGGLE_ACTIVE_CATEGORY: "toggle_active_category",
    TOGGLE_FEATURED_CATEGORY: "toggle_featured_category",
    TOGGLE_DEFAULT_CATEGORY: "toggle_default_category",
  },
  NEWS: {
    ADD_NEWS_ARTICLE: "add_news_article",
    VIEW_ALL_NEWS_ARTICLES: "view_all_news_articles",
    EDIT_NEWS_ARTICLE: "edit_news_article",
    DELETE_NEWS_ARTICLE: "delete_news_article",
    TOGGLE_ACTIVE_NEWS_ARTICLE: "toggle_active_news_article",
    TOGGLE_FEATURED_NEWS_ARTICLE: "toggle_featured_news_article",
  },
  NEWS_CATEGORY: {
    ADD_NEWS_CATEGORY: "add_news_category",
    VIEW_ALL_NEWS_CATEGORIES: "view_all_news_categories",
    EDIT_NEWS_CATEGORY: "edit_news_category",
    DELETE_NEWS_CATEGORY: "delete_news_category",
    TOGGLE_ACTIVE_NEWS_CATEGORY: "toggle_active_news_category",
    TOGGLE_FEATURED_NEWS_CATEGORY: "toggle_featured_news_category",
    TOGGLE_DEFAULT_NEWS_CATEGORY: "toggle_default_news_category",
  },
  CAREERS: {
    ADD_NEW_JOB: "add_new_job",
    VIEW_ALL_JOBS: "view_all_jobs",
    EDIT_JOB: "edit_job",
    DELETE_JOB: "delete_job",
    TOGGLE_ACTIVE_JOB: "toggle_active_job",
    TOGGLE_FEATURED_JOB: "toggle_featured_job",
  },
  FILE: {
    ADD_FILE: "add_file",
    VIEW_ALL_FILES: "view_all_files",
    DELETE_FILE: "delete_file",
    DOWNLOAD_FILE: "download_file",
    TOGGLE_DEFAULT_FILE: "toggle_default_file",
    FILE_DETAILS: "file_details",
  },
  STAFF: {
    ADD_STAFF: "add_staff",
    VIEW_ALL_STAFFS: "view_all_staffs",
    EDIT_STAFF: "edit_staff",
    DELETE_STAFF: "delete_staff",
    ADD_STAFF_ROLE: "add_staff_role",
    VIEW_STAFF_ROLES: "view_staff_roles",
    EDIT_STAFF_ROLE: "edit_staff_role",
    DELETE_STAFF_ROLE: "delete_staff_role",
  },
  LANGUAGE: {
    ADD_LANGUAGE: "add_language",
    VIEW_ALL_LANGUAGES: "view_all_languages",
    EDIT_LANGUAGE: "edit_language",
    DELETE_LANGUAGE: "delete_language",
    TOGGLE_ACTIVE_LANGUAGE: "toggle_active_language",
    TOGGLE_RTL_LANGUAGE: "toggle_rtl_language",
    TOGGLE_DEFAULT_LANGUAGE: "toggle_default_language",
  },
  WEBSITE_SETUP: {
    HEADER_SETUP: "header_setup",
    FOOTER_SETUP: "footer_setup",
    GENERAL_SETTINGS: "general_settings",
  },
  MENU_MANAGEMENT: {
    ADD_MENU: "add_menu",
    EDIT_MENU: "edit_menu",
    DELETE_MENU: "delete_menu",
    VIEW_ALL_MENUS: "view_all_menus",
    TOGGLE_PRODUCT_MENU: "toggle_product_menu",
    TOGGLE_ACTIVE_MENU: "toggle_active_menu",
  },
};
